kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  controllerManager:
    extraArgs:
      "feature-gates": "CSIInlineVolume=true"
  apiServer:
    extraArgs:
      "feature-gates": "CSIInlineVolume=true"
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "CSIInlineVolume=true"
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - containerPath: /etc/kubernetes/azure.json
    hostPath: /tmp/azure.json
