language: go
go_import_path: github.com/kubernetes-sigs/azurefile-csi-driver
dist: bionic

env:
  global:
    - GO111MODULE=on

go:
  - "1.11.4"

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls
  - GO111MODULE=off go get github.com/rexray/gocsi/csc
  - sudo apt update && sudo apt install cifs-utils procps -y

jobs:
  include:
    - stage: test
      name: "build test"
      script:
        - make azurefile
        - make azurefile-windows
        - go test -covermode=count -coverprofile=profile.cov ./pkg/...
    - stage: test
      name: "code verification test"
      script:
        - hack/verify-all.sh   
        - make verify-modules        
    - stage: test
      name: "Sanity Test"
      script: make sanity-test
      # after_failure: TRAVIS_TEST_RESULT=0
    - stage: test
      name: "Integration Test"
      script:
        - make azurefile
        - make integration-test
      
