---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driver.name }}
spec:
  attachRequired: {{ .Values.controller.attachRequired }}
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  {{- if .Values.feature.enableFSGroupPolicy}}
  fsGroupPolicy: File
  {{- end}}
