---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: file.csi.azure.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-smb
  labels:
    app: aspnet
spec:
  replicas: 1
  template:
    metadata:
      name: aspnet
      labels:
        app: aspnet
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: aspnet
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          volumeMounts:
            - name: smb
              mountPath: "/mnt/smb"
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb
  selector:
    matchLabels:
      app: aspnet
