---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions: "vers=3.0,dir_mode=0777,file_mode=0777"
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: arbitrary-volumeid  # make sure it's a uniqe id
    volumeAttributes:
      source: "//STORAGE-ACCOUNT.file.core.windows.net/SHARE-NAME"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
