---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: arbitrary-volumeid  # make sure it's a uniqe id
    volumeAttributes:
      shareName: EXISTING_FILE_SHARE_NAME  # only file share name, don't use full path
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
