---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
  protocol: nfs  # use "fsType: nfs" in v0.8.0
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
