---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: azurefile-volume-snapshot
spec:
  snapshotClassName: csi-azurefile-vsc
  source:
    name: pvc-azurefile
    kind: PersistentVolumeClaim
